default: &default
  adapter: <%= ENV.fetch("DATABASE_ADAPTER") %>
  encoding: unicode
  reconnect: true
  pool: <%= ENV.fetch("DATABASE_POOL") %>
  username: <%= ENV.fetch("DATABASE_USERNAME") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>

development:
  <<: *default
  database: 100km_development

test:
  <<: *default
  database: 100km_test

staging:
  <<: *default
  database: 100km_staging

production:
  <<: *default
  database: 100km_production
